name: Manual Action
run-name: Run by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: 'Greeting message'
        required: true
        default: 'Hello, World!'
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # 中間環境変数。
      ACTOR: ${{ github.actor }}
    steps:
      - name: Say hello
        run: echo "${{ github.event.inputs.greeting }}"

      - name: User Context
        run: |
          # github: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          echo "${{ github.actor }} triggered by ${{ github.event }} on ${{ github.repository }}"

          # runner: https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
          echo "${{ runner }}"
          echo "${{ runner.os }}, ${{ runner.arch }}"

      - name: Env
        run: |
          # context
          echo "${{ env.BRANCH }}"
          # environment
          echo "${GITHUB_ACTOR}"

      - name: Intermediate Env
        run: |
          echo "${ACTOR}"

      - name: Func
        run: printenv | grep '_FUNC'
        env:
          # https://docs.github.com/ja/actions/learn-github-actions/expressions#functions
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'Hel') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'llo') }}

      - name: Secret
        run: |
          echo "${{ secrets.TOP_TOP_SECRET }}"
          echo "${{ secrets.TOP_TOP_SECRET }}" | grep PI

      - name: Literals
        run: |
          printenv | grep '_LITERAL'
        env:
          # Shell にはない概念としてリテラルがある。
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 42 }}
          LITERAL_STRING: ${{ 'Hello, World!' }}
          # string 型には省略がある！
          # https://docs.github.com/ja/actions/learn-github-actions/expressions#literals
          LITERAL_OMIT_STRING: 'Hello, World!'


  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR comment
        run: |
          # gh があらかじめインストールされている。
          gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
